version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd backend && npm install
      - cd .. && ls 
      - cd frontend && npm install
  build:
    commands:
      - echo Build started on `date`
      - cd frontend && npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'ahh.yml'
  base-directory: 'build'
  discard-paths: yes
  